TITLE Multiplicação 
.MODEL SMALL
.STACK 100h
.DATA
    MSG1 DB 'Digite o multiplicando:$',10,13
    MSG2 DB 10,13,'Digite o multiplicador:$',10,13
    MSG3 DB 10,13,'Produto:$'
.CODE
MAIN PROC
    ;PERMITE ACESSO AOS DADOS DE .DATA
    MOV AX,@DATA
    MOV DS,AX
    ;EXIBE A STRING "MSG1"
    MOV AH,9
    LEA DX,MSG1 
    INT 21H
    ;LÊ UM CARACTER DIGITADO E SALVA EM AL
    MOV AH,1
    INT 21H
    ;TRANSFORMA O CARACTER DA TABELA ASCII PARA VALOR NÚMERICO
    AND AL,0FH
    ;SALVA O VALOR DE AL EM BL
    MOV BL,AL
    ;EXIBE A STRING "MSG2"
    MOV AH,9
    LEA DX,MSG2
    INT 21H
    ;LÊ UM CARACTER DIGITADO E SALVA EM AL
    MOV AH,1
    INT 21H
    ;TRANSFORMA O CARACTER DA TABELA ASCII PARA VALOR NUMÉRICO
    AND AL,0FH
    ;SALVA O VALOR DE AL EM CL
    MOV CL,AL
    ;ADICIONA O VALOR DE BL EM BH ATÉ CX SER 0
   SOMA: 
    ADD BH,BL
    LOOP SOMA
    ;EXIBE A STRING "MSG3"
    MOV AH,9
    LEA DX,MSG3
    INT 21H
    ;SALVA O VALOR DE BH EM DL
    MOV DL,BH
    ;TRANSFORMA O VALOR NUMÉRICO PARA O CARACTER DA TABELA ASCII
    OR DL,30h
    ;IMPRIME O CARACTER SALVO EM DL
    MOV AH,2
    INT 21H
    ;INTERROMPE O CÓDIGO PARA FINALIZÁ-LO
    MOV AH,4Ch
    INT 21H

MAIN ENDP
END MAIN




