TITLE Multiplicação 
.MODEL SMALL
.STACK 100h
.DATA
    MSG1 DB 'Digite o dividendo:$',10,13
    MSG2 DB 10,13,'Digite o divisor:$',10,13
    MSG3 DB 10,13,'Quociente:$',10,13
    MSG4 DB 10,13,'Resto:$'
.CODE
MAIN PROC
    ;PERMITE ACESSO AOS DADOS DE .DATA
    MOV AX,@DATA
    MOV DS,AX
    ;EXIBE A STRING "MSG1"
    MOV AH,9
    LEA DX,MSG1 
    INT 21H
    ;LÊ UM CARACTER DIGITADO E SALVA EM AL
    MOV AH,1
    INT 21H
    ;TRANSFORMA O CARACTER DA TABELA ASCII PARA VALOR NÚMERICO 
    AND AL,0FH
    ;SALVA O VALOR DE AL EM BL
    MOV BL,AL
    ;EXIBE A STRING "MSG2"
    MOV AH,9
    LEA DX,MSG2
    INT 21H
    ;LÊ UM CARACTER DIGITADO E SALVA EM AL
    MOV AH,1
    INT 21H
    ;TRANSFORMA O CARACTER DA TABELA ASCII PARA VALOR NUMÉRICO 
    AND AL,0FH
    ;SALVA O VALOR DE AL EM BH
    MOV BH,AL
    ;ZERA O VALOR DO CONTADOR CX
    XOR CL,CL
    ;SUBTRAI DE BL A QUANTIDADE DE VEZES NECESSÁRIA DE BH ATÉ SEU VALOR SER MENOR QUE TAL, INCREMENTANDO 1 EM CL PARA CADA RETIRADA
   SUBTRAÇÃO: 
    SUB BL,BH
    INC CL
    CMP BL,BH
    JAE SUBTRAÇÃO
    ;EXIBE A STRING "MSG3"
    MOV AH,9
    LEA DX,MSG3
    INT 21H
    ;SALVA O VALOR DE CL EM DL
    MOV DL,CL
    ;TRANSFORMA O VALOR NUMÉRICO PARA O CARACTER DA TABELA ASCII
    OR DL,30h
    ;IMPRIME O CARACTER SALVO EM DL
    MOV AH,2
    INT 21H
    ;EXIBE A STRING "MSG4"
    MOV AH,9
    LEA DX,MSG4
    INT 21H
    ;SALVA O VALOR DE BL EM DL
    MOV DL,BL
    ;TRANSFORMA O VALOR NUMÉRICO PARA O CARACTER DA TABELA ASCII
    OR DL,30h
    ;IMPRIME O CARACTER SALVO EM DL
    MOV AH,2
    INT 21H
    ;INTERROMPE O CÓDIGO PARA FINALIZÁ-LO
    MOV AH,4Ch
    INT 21H

MAIN ENDP
END MAIN