TITLE Numero2    
.MODEL SMALL
.STACK 100h
.DATA   
    MSG1 DB "Digite um caractere:$"
    DES DB 10,13,"O caractere digitado e um caractere desconhecido.$"
    LET DB 10,13,"O caractere digitado e uma letra.$"
    NUM DB 10,13,"O caractere digitado e um numero.$"
.CODE
MAIN PROC
    ;PERMITE ACESSO AOS DADOS DE .DATA
    MOV AX,@DATA
    MOV DS,AX
    ;EXIBE NA TELA A MENSAGEM 1 "MSG1"
    MOV AH,9
    MOV DX,OFFSET MSG1  
    INT 21h
    ;LÊ UM CARACTER DO TECLADO E SALVA ELE REGISTRADOR     
    MOV AH,1
    INT 21h
    ;COPIA O CONTEUDO DE AL EM BL
    MOV BL,AL
    ;COMPARA O CARACTER COPIADO EM BL COM O VALOR 48 (CÓDIGO DO CARACTER "0" DA TABELA ASCII)
    CMP BL,48
    ;SE O CARACTER FOR MENOR QUE 48 ("0"), O CÓDIGO SALTARÁ PARA O RÓTULO "DESCONHECIDO"
    JB DESCONHECIDO
    ;COMPARA O CARACTER COPIADO EM BL COM O VALOR 57 (CÓDIGO DO CARACTER "9" DA TABELA ASCII)
    CMP BL,57
    ;SE O CARACTER FOR MAIOR QUE 57 ("9"), O CÓDIGO SALTARÁ PARA O RÓTULO "TALVEZLETRA"
    JA TALVEZLETRA
    ;O CARACTER SERA DITO NA TELA COMO SENDO UM NÚMERO
    MOV AH,9
    MOV DX,OFFSET NUM
    INT 21h
    ;SALTA PARA O RÓTULO "FIM"
    JMP FIM
    ;DEFINE O RÓTULO "TALVEZLETRA"
TALVEZLETRA:
    ;COMPARA O CARACTER COPIADO EM BL COM O VALOR 65 (CÓDIGO DO CARACTER "A" DA TABELA ASCII)
    CMP BL,65
    ;SE O CARACTER FOR MENOR QUE 65 ("A"), O CÓDIGO SALTARÁ PARA O RÓTULO "DESCONHECIDO"
    JB DESCONHECIDO
    ;COMPARA O CARACTER COPIADO EM BL COM O VALOR 90 (CÓDIGO DO CARACTER "Z" DA TABELA ASCII)
    CMP BL,90
    ;SE O CARACTER FOR MENOR OU IGUAL A 90 ("Z"), O CÓDIGO SALTARÁ PARA O RÓTULO "LETRA"
    JBE LETRA
    ;COMPARA O CARACTER COPIADO EM BL COM O VALOR 97 (CÓDIGO DO CARACTER "a" DA TABELA ASCII)
    CMP BL,97
    ;SE O CARACTER FOR MENOR QUE 97 ("a"), O CÓDIGO SALTARÁ PARA O RÓTULO "DESCONHECIDO"
    JB DESCONHECIDO
    ;COMPARA O CARACTER COPIADO EM BL COM O VALOR 122 (CÓDIGO DO CARACTER "z" DA TABELA ASCII)
    CMP BL,122
    ;SE O CARACTER FOR MENOR OU IGUAL A 122 ("z"), O CÓDIGO SALTARÁ PARA O RÓTULO "LETRA"
    JBE LETRA
    ;SALTA INCONDICIONALMENTE PARA O RÓTULO "DESCONHECIDO"
    JMP DESCONHECIDO
    ;DEFINE O RÓTULO "DESCONHECIDO"
DESCONHECIDO:
    ;O CARACTER SERA DITO NA TELA COMO DESCONHECIDO
    MOV AH,9
    MOV DX,OFFSET DES
    INT 21h
    JMP FIM
    ;DEFINE O RÓTULO "LETRA"
LETRA:
    ;O CARACTER SERA DITO NA TELA COMO SENDO UMA LETRA
    MOV AH,9
    MOV DX,OFFSET LET
    INT 21h
    JMP FIM
    ;DEFINE O RÓTULO "FIM"
FIM:
    ;FINALIZA O PROGRAMA
    MOV AH,4Ch
    INT 21h

MAIN ENDP
END MAIN

