TITLE Numero    
.MODEL SMALL
.STACK 100h
.DATA   
    MSG1 DB "Digite um caractere:$"
    SIM DB 10,13,"O caractere digitado e um numero.$"
    NAO DB 10,13,"O caractere digitado nao e um numero.$"
.CODE
MAIN PROC 
    ;PERMITE ACESSO AOS DADOS DE .DATA
    MOV AX,@DATA
    MOV DS,AX
    ;EXIBE NA TELA A MENSAGEM 1 "MSG1"
    MOV AH,9
    MOV DX,OFFSET MSG1  
    INT 21h
    ;LÊ UM CARACTER DO TECLADO E SALVA ELE REGISTRADOR     
    MOV AH,1
    INT 21h
    ;COPIA O CONTEUDO DE AL EM BL
    MOV BL,AL
    ;COMPARA O CARACTER COPIADO EM BL COM O VALOR 48 (CÓDIGO DO CARACTER "0" DA TABELA ASCII)
    CMP BL,48
    ;SE O CARACTER FOR MENOR QUE 48 ("0"), O CÓDIGO SALTARÁ PARA O RÓTULO "NAOENUMERO"
    JB NAOENUMERO
    ;COMPARA O CARACTER COPIADO EM BL COM O VALOR 57 (CÓDIGO DO CARACTER "9" DA TABELA ASCII)
    CMP BL,57
    ;SE O CARACTER FOR MAIOR QUE 57 ("9"), O CÓDIGO SALTARÁ PARA O RÓTULO "NAOENUMERO"
    JA NAOENUMERO
    ;SE CHEGAR ATÉ AQUI, O CARACTER SERÁ EXIBIDO NA TELA COMO NÚMERO
    MOV AH,9
    MOV DX,OFFSET SIM
    INT 21h
    ;SALTA PARA O RÓTULO FIM
    JMP FIM
    ;DEFINE O RÓTULO "NAOENUMERO"
NAOENUMERO:
    ;O CARACTER SERA DITO NA TELA COMO NÃO SENDO UM NÚMERO
    MOV AH,9
    MOV DX,OFFSET NAO
    INT 21h
    ;DEFINE O RÓTULO "FIM"
FIM:
    ;FINALIZA O PROGRAMA
    MOV AH, 4Ch
    INT 21h

MAIN ENDP
END MAIN
